version: "3.9"

services:
  orbita-ui:
    build:
      context: .
      dockerfile: .docker/app/orbita-ui.prod.Dockerfile
      args:
        NODE_MAJOR: 14
        YARN_VERSION: 1.22.5
        APP_ROOT: /app
        APP_HOSTNAME: docker-test-713
      labels:
        project-name: "orbita-ui-test"
        environment: "staging"
        maintainer: "bayburin@iss-reshetnev.ru"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    stdin_open: true
    tty: true
    mac_address: 56:b7:91:c1:21:ee
    networks:
      macvlan:
        ipv4_address: 10.0.9.188

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: ens224
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1
