module.exports = {
  projects: [
    '<rootDir>/apps/orbita-ui',
    '<rootDir>/libs/orbita-ui/domain-logic',
    '<rootDir>/libs/orbita-ui/ui',
    '<rootDir>/libs/orbita-ui/feature-listing',
    '<rootDir>/libs/orbita-ui/shell',
    '<rootDir>/libs/orbita-ui/feature-sd-request-wizzard',
    '<rootDir>/libs/shared/environment',
    '<rootDir>/libs/orbita-ui/utils',
    '<rootDir>/libs/shared/domain-logic',
    '<rootDir>/libs/shared/assets',
    '<rootDir>/libs/orbita-ui/feature-sd-request-overview',
    '<rootDir>/libs/orbita-ui/feature-ticket',
    '<rootDir>/libs/orbita-ui/foo',
    '<rootDir>/libs/orbita-ui/feature-employee-listing',
    '<rootDir>/libs/orbita-ui/feature-employee',
    '<rootDir>/libs/orbita-ui/feature-employee-overview',
    '<rootDir>/libs/orbita-ui/feature-svt-item',
    '<rootDir>/libs/orbita-ui/feature-svt-item-listing',
  ],
};
